name: SignDoctor
main: signdoctor.SignDoctor
version: 1.1

commands:
  editSign:
    description: Edit the currently selected sign. Use _ for space and \n to skip lines. These can be changed in the config.
    usage: /<command> [LineText1] [LineText2] [LineText3] [LineText4]
  editSignln:
    description: Edit the currently selected sign's line. You can use normal spaces. Lines range from 1 to 4.
    usage: /<command> [Line1-4] [Optional Text...]
  appendToSign:
    description: Append text to the currently selected sign's line. You can use normal spaces. Lines range from 1 to 4.
    usage: /<command> [Line1-4] [Text...]
  prependToSign:
    description: Prepend text to the currently selected sign's line. You can use normal spaces. Lines range from 1 to 4.
    usage: /<command> [Line1-4] [Text...]
  replaceSign:
    description: Replaces the first text occurrence which matches the regular expression on all lines.
    usage: /<command> [Regex] [Option Text]
  replaceSignAll:
    description: Replaces all text occurrences which matches the regular expression on all lines.
    usage: /<command> [Regex] [Option Text]
  replaceln:
    description: Replaces the first text occurrence which matches the regular expression.
    usage: /<command> [Line1-4] [Regex] [Optional Text]
  replacelnAll:
    description: Replaces all text occurrences which matches the regular expression.
    usage: /<command> [Line1-4] [Regex] [Optional Text]
  switchln:
    description: Switches two lines around.
    usage: /<command> [Line1-4] [Line1-4]
  toggleSignEdit:
    description: Toggle the ability to edit signs.
    usage: /<command>
  clearSign:
    description: Clears the active sign's text.
    usage: /<command>
  copySign:
    description: Copies the active sign's text.
    usage: /<command>
  cutSign:
    description: Cuts the active sign's text.
    usage: /<command>
  pasteSign:
    description: Pastes the stored sign text to the active sign.
    usage: /<command>
  clearln:
    description: Clears the active sign's line.
    usage: /<command> [Line1-4]
  copyln:
    description: Copies the active sign's line.
    usage: /<command> [Line1-4]
  cutln:
    description: Cuts the active sign's line.
    usage: /<command> [Line1-4]
  pasteln:
    description: Pastes the stored sign line to the active sign line.
    usage: /<command> [Line1-4]
  tpToSign:
    description: Teleports you to the active sign.
    usage: /<command>
  tpBackFromSign:
    description: Teleports you back from the active sign. Must have used 'tpToSign' first.
    usage: /<command>

permissions:
  signdoctor.signediting:
    description: Allows the editing of signs.
    default: op
  signdoctor.teleporting:
    description: Allows the use of tpToSign and tpBackFromSign.
    default: op
