name: Sign Editor
main: main.SignEditor
version: 1.0

commands:
  editSign:
    description: Edit the currently selected sign. Use _ for space and \n to leave an empty line.
    usage: /<command> [LineText1] [LineText2] [LineText3] [LineText4]
  editSignln:
    description: Edit the currently selected sign's line. You can use normal spaces. Lines range from 1 to 4.
    usage: /<command> [Line1-4] [Text...]
  toggleSignEdit:
    description: Toggle the ability to edit signs.
    usage: /<command>
  clearSign:
    description: Clears the active sign's text.
    usage: /<command>
  copySign:
    description: Copies the active sign's text.
    usage: /<command>
  cutSign:
    description: Cuts the active sign's text.
    usage: /<command>
  pasteSign:
    description: Pastes the stored sign text to the active sign.
    usage: /<command>
  tpToSign:
    description: Teleports you to the active sign.
    usage: /<command>
  tpBackFromSign:
    description: Teleports you back from the active sign. Must have used 'tpToSign' first.
    usage: /<command>